name: PracticePlugin
main: main.Main
version: 1.0.0
api-version: 1.17

commands:
  queue:
    description: join or leave queue!
    usage: /queue [join/leave]

  refill:
    description: Refills chest in 0,5,0, sender's world for test. If chest doesn't exists, creates one.
    usage: /refill

  reset:
    description: reset "pvpmap" world, for test.
    usage: /reset

  perks:
    description: show perks.
    usage: /perks